//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao
    {
        public int user_in_id { get; set; }
        public int ava_in_ratings { get; set; }
        public string ava_st_comentario { get; set; }
        public int test_in_id { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_teste tb_teste { get; set; }
    }
}
